/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.DoctorRole;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Enterprise.PharmacyEnterprise;
import Model.Network.Network;
import Model.Organization.DoctorOrganization;
import Model.Organization.DrugSalesOrganization;
import Model.Organization.Organization;
import Model.Role.VaccineRequest;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.PatientDoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class RequestVaccinationJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientDoctorWorkRequest patientDoctorWorkRequest;
    private DoctorOrganization organization;
    private EcoSystem ecoSystem;
    /**
    /**
     * Creates new form RequestVaccinationJPanel
     */
    public RequestVaccinationJPanel(JPanel userProcessContainer, UserAccount userAccount, DoctorOrganization organization, Enterprise enterprise, PatientDoctorWorkRequest patientDoctorWorkRequest,EcoSystem ecoSystem) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organization = (DoctorOrganization)organization;
        this.enterprise = enterprise;
   
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;

        this.patientDoctorWorkRequest = patientDoctorWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quantityJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vaccineNameJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("vaccineName");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        add(quantityJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 121, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Request Vaccination");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        requestTestJButton.setText("Add");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));
        add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 108, 121, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        // TODO add your handling code here:
        //
        //        String drugName = drugNameJTextField.getText();
        //        String drugQuantity = quantityJTextField.getText();

        String vaccineName = vaccineNameJTextField.getText();
    String quantityStr = quantityJTextField.getText();

    // Validation for empty fields
    if (vaccineName.isEmpty() || quantityStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter all fields");
        return;
    }

    int quantity;
    // Validate if quantity is a valid number
    try {
        quantity = Integer.parseInt(quantityStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Quantity must be a number");
        return;
    }

    // Set default values for other fields
    String sender = userAccount.getUsername(); // Assuming `userAccount` represents the current user
    String receiver = "Patient"; // Default receiver or dynamic assignment based on context
    String status = "Pending"; // Initial status of the request
    String date = new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()); // Current date

    // Create a new VaccineRequest object
    VaccineRequest newRequest = new VaccineRequest(vaccineName, quantity, sender, receiver, status, date);

    // Add the request to the shared list (assuming a shared data structure is used)
    utils.SharedData.vaccineRequestList.add(newRequest);

    // Display success message
    JOptionPane.showMessageDialog(null, "Request added successfully!");
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorHomePageJPanel dwjp = (DoctorHomePageJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField quantityJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField vaccineNameJTextField;
    // End of variables declaration//GEN-END:variables
}
