/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.DonorRole;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.DonorOrganization;
import Model.Organization.PatientOrganization;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author divya
 */
public class ManageMyProfileJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;    
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DonorOrganization donorOrganization;
    //private PatientDirectory patientDirectory;
    /**
     * Creates new form ManageMyProfileJPanel
     */
    public ManageMyProfileJPanel(JPanel userProcessContainer,UserAccount userAccount, DonorOrganization donorOrganization, Enterprise enterprise,EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.donorOrganization = (DonorOrganization)donorOrganization;
        this.enterprise = enterprise;
        //this.patientDirectory = patientDirectory;) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        createMyProfileJButton = new javax.swing.JButton();
        viewUpdateMyProfileJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Manage My Profile");

        createMyProfileJButton.setText("Create My Profile");
        createMyProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMyProfileJButtonActionPerformed(evt);
            }
        });

        viewUpdateMyProfileJButton.setText("View and Update My Profile");
        viewUpdateMyProfileJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateMyProfileJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(createMyProfileJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(viewUpdateMyProfileJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backJButton))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel9)
                .addGap(60, 60, 60)
                .addComponent(createMyProfileJButton)
                .addGap(32, 32, 32)
                .addComponent(viewUpdateMyProfileJButton)
                .addGap(57, 57, 57)
                .addComponent(backJButton)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createMyProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMyProfileJButtonActionPerformed
        // TODO add your handling code here:
        CreateMyProfileJPanel panel = new CreateMyProfileJPanel(userProcessContainer,userAccount,donorOrganization,enterprise,ecoSystem);
        userProcessContainer.add("CreateMyProfileJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createMyProfileJButtonActionPerformed

    private void viewUpdateMyProfileJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateMyProfileJButtonActionPerformed
        // TODO add your handling code here:
        ViewUpdateMyProfileJPanel panel = new ViewUpdateMyProfileJPanel(userProcessContainer,userAccount,donorOrganization,enterprise,ecoSystem);
        userProcessContainer.add("ViewUpdateMyProfileJPane", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewUpdateMyProfileJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createMyProfileJButton;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton viewUpdateMyProfileJButton;
    // End of variables declaration//GEN-END:variables
}
