/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.DonorRole;

import Model.Donor.Donor;
import Model.Donor.Record;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Organization.DonorOrganization;
import Model.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author divya
 */
public class ViewUpdateRecordDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;    
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DonorOrganization donorOrganization;
    private Donor donor;
    private Record record;
    /**

    /**
     * Creates new form ViewUpdateRecordJPanel
     */
    public ViewUpdateRecordDetailsJPanel(JPanel userProcessContainer,UserAccount userAccount, DonorOrganization donorOrganization, Enterprise enterprise,EcoSystem ecoSystem,Record record) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.donorOrganization = (DonorOrganization)donorOrganization;
        this.enterprise = enterprise;
        this.donor= userAccount.getDonor();
        this.record = record;
        populateDetails();
    }

    private void populateDetails() {
        bloodGroupJTextField.setText(String.valueOf(record.getBloodGroup()));
        organDonorJTextField.setText(String.valueOf(record.getOrganDonor()));
        medicalHistoryJTextField.setText(String.valueOf(record.getMedicalHistory()));
        lastDonationDateJTextField.setText(String.valueOf(record.getLastDonationDate()));        
        
    }
    /**) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        saveJButton1 = new javax.swing.JButton();
        saveJButton2 = new javax.swing.JButton();
        lblBloodGroup = new javax.swing.JLabel();
        bloodGroupJTextField = new javax.swing.JTextField();
        lblOrganDonor = new javax.swing.JLabel();
        organDonorJTextField = new javax.swing.JTextField();
        lblMedicalHistory = new javax.swing.JLabel();
        medicalHistoryJTextField = new javax.swing.JTextField();
        lblLastDonationDate = new javax.swing.JLabel();
        lastDonationDateJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 204));
        jLabel17.setText("View Record Details");

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        saveJButton1.setText("Save");
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });

        saveJButton2.setText("Update");
        saveJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton2ActionPerformed(evt);
            }
        });

        lblBloodGroup.setText("Blood Group");

        bloodGroupJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupJTextFieldActionPerformed(evt);
            }
        });

        lblOrganDonor.setText("Organ Donor");

        lblMedicalHistory.setText("Medical History");

        medicalHistoryJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalHistoryJTextFieldActionPerformed(evt);
            }
        });

        lblLastDonationDate.setText("Last Donation Date");

        lastDonationDateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDonationDateJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOrganDonor)
                        .addGap(89, 89, 89)
                        .addComponent(organDonorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveJButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLastDonationDate)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(medicalHistoryJTextField)
                            .addComponent(lastDonationDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveJButton2))))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodGroupJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloodGroup))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organDonorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganDonor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicalHistoryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicalHistory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastDonationDateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastDonationDate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backJButton)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveJButton1)
                            .addComponent(saveJButton2))
                        .addGap(0, 55, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton1ActionPerformed

    private void saveJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveJButton2ActionPerformed

    private void bloodGroupJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupJTextFieldActionPerformed

    private void medicalHistoryJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalHistoryJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalHistoryJTextFieldActionPerformed

    private void lastDonationDateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDonationDateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastDonationDateJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodGroupJTextField;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JTextField lastDonationDateJTextField;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblLastDonationDate;
    private javax.swing.JLabel lblMedicalHistory;
    private javax.swing.JLabel lblOrganDonor;
    private javax.swing.JTextField medicalHistoryJTextField;
    private javax.swing.JTextField organDonorJTextField;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JButton saveJButton2;
    // End of variables declaration//GEN-END:variables
}
